package endpoint

// 定义所有接口的元数据

var AllEndpoints = []*Endpoint{
	// ==================== Auth 认证 ====================
	{
		Name:   "auth.login",
		Path:   "/api/v1/auth/login",
		Method: "POST",
		Domain: "auth",
		Action: "login",
		Desc:   "用户登录",
	},
	{
		Name:   "auth.logout",
		Path:   "/api/v1/auth/logout",
		Method: "POST",
		Domain: "auth",
		Action: "logout",
		Desc:   "用户登出",
	},
	{
		Name:   "auth.refresh",
		Path:   "/api/v1/auth/refresh",
		Method: "POST",
		Domain: "auth",
		Action: "refresh",
		Desc:   "刷新 Token",
	},

	// ==================== User 用户 ====================
	{
		Name:   "user.create",
		Path:   "/api/v1/user",
		Method: "POST",
		Domain: "user",
		Action: "create",
		Desc:   "创建用户",
	},
	{
		Name:   "user.list",
		Path:   "/api/v1/user",
		Method: "GET",
		Domain: "user",
		Action: "list",
		Desc:   "用户列表",
	},
	{
		Name:   "user.detail",
		Path:   "/api/v1/user/:id",
		Method: "GET",
		Domain: "user",
		Action: "detail",
		Desc:   "用户详情",
	},
	{
		Name:   "user.update",
		Path:   "/api/v1/user/:id",
		Method: "PUT",
		Domain: "user",
		Action: "update",
		Desc:   "更新用户",
	},
	{
		Name:   "user.delete",
		Path:   "/api/v1/user/:id",
		Method: "DELETE",
		Domain: "user",
		Action: "delete",
		Desc:   "删除用户",
	},
	{
		Name:   "user.changePassword",
		Path:   "/api/v1/user/:id/password",
		Method: "PUT",
		Domain: "user",
		Action: "changePassword",
		Desc:   "修改密码",
	},

	// ==================== Department 部门 ====================
	{
		Name:   "department.create",
		Path:   "/api/v1/department",
		Method: "POST",
		Domain: "department",
		Action: "create",
		Desc:   "创建部门",
	},
	{
		Name:   "department.list",
		Path:   "/api/v1/department",
		Method: "GET",
		Domain: "department",
		Action: "list",
		Desc:   "部门列表",
	},
	{
		Name:   "department.detail",
		Path:   "/api/v1/department/:id",
		Method: "GET",
		Domain: "department",
		Action: "detail",
		Desc:   "部门详情",
	},
	{
		Name:   "department.update",
		Path:   "/api/v1/department/:id",
		Method: "PUT",
		Domain: "department",
		Action: "update",
		Desc:   "更新部门",
	},
	{
		Name:   "department.delete",
		Path:   "/api/v1/department/:id",
		Method: "DELETE",
		Domain: "department",
		Action: "delete",
		Desc:   "删除部门",
	},

	// ==================== Role 角色 ====================
	{
		Name:   "role.create",
		Path:   "/api/v1/role",
		Method: "POST",
		Domain: "role",
		Action: "create",
		Desc:   "创建角色",
	},
	{
		Name:   "role.list",
		Path:   "/api/v1/role",
		Method: "GET",
		Domain: "role",
		Action: "list",
		Desc:   "角色列表",
	},
	{
		Name:   "role.detail",
		Path:   "/api/v1/role/:id",
		Method: "GET",
		Domain: "role",
		Action: "detail",
		Desc:   "角色详情",
	},
	{
		Name:   "role.update",
		Path:   "/api/v1/role/:id",
		Method: "PUT",
		Domain: "role",
		Action: "update",
		Desc:   "更新角色",
	},
	{
		Name:   "role.delete",
		Path:   "/api/v1/role/:id",
		Method: "DELETE",
		Domain: "role",
		Action: "delete",
		Desc:   "删除角色",
	},

	// ==================== Supplier 供应商 ====================
	{
		Name:   "supplier.create",
		Path:   "/api/v1/supplier",
		Method: "POST",
		Domain: "supplier",
		Action: "create",
		Desc:   "创建供应商",
	},
	{
		Name:   "supplier.list",
		Path:   "/api/v1/supplier",
		Method: "GET",
		Domain: "supplier",
		Action: "list",
		Desc:   "供应商列表",
	},
	{
		Name:   "supplier.detail",
		Path:   "/api/v1/supplier/:id",
		Method: "GET",
		Domain: "supplier",
		Action: "detail",
		Desc:   "供应商详情",
	},
	{
		Name:   "supplier.update",
		Path:   "/api/v1/supplier/:id",
		Method: "PUT",
		Domain: "supplier",
		Action: "update",
		Desc:   "更新供应商",
	},
	{
		Name:   "supplier.delete",
		Path:   "/api/v1/supplier/:id",
		Method: "DELETE",
		Domain: "supplier",
		Action: "delete",
		Desc:   "删除供应商",
	},

	// ==================== Client 客户 ====================
	{
		Name:   "client.create",
		Path:   "/api/v1/client",
		Method: "POST",
		Domain: "client",
		Action: "create",
		Desc:   "创建客户",
	},
	{
		Name:   "client.list",
		Path:   "/api/v1/client",
		Method: "GET",
		Domain: "client",
		Action: "list",
		Desc:   "客户列表",
	},
	{
		Name:   "client.detail",
		Path:   "/api/v1/client/:id",
		Method: "GET",
		Domain: "client",
		Action: "detail",
		Desc:   "客户详情",
	},
	{
		Name:   "client.update",
		Path:   "/api/v1/client/:id",
		Method: "PUT",
		Domain: "client",
		Action: "update",
		Desc:   "更新客户",
	},
	{
		Name:   "client.delete",
		Path:   "/api/v1/client/:id",
		Method: "DELETE",
		Domain: "client",
		Action: "delete",
		Desc:   "删除客户",
	},

	// ==================== Material 原材料 ====================
	{
		Name:   "material.create",
		Path:   "/api/v1/material",
		Method: "POST",
		Domain: "material",
		Action: "create",
		Desc:   "创建原材料",
	},
	{
		Name:   "material.list",
		Path:   "/api/v1/material",
		Method: "GET",
		Domain: "material",
		Action: "list",
		Desc:   "原材料列表",
	},
	{
		Name:   "material.detail",
		Path:   "/api/v1/material/:id",
		Method: "GET",
		Domain: "material",
		Action: "detail",
		Desc:   "原材料详情",
	},
	{
		Name:   "material.update",
		Path:   "/api/v1/material/:id",
		Method: "PUT",
		Domain: "material",
		Action: "update",
		Desc:   "更新原材料",
	},
	{
		Name:   "material.delete",
		Path:   "/api/v1/material/:id",
		Method: "DELETE",
		Domain: "material",
		Action: "delete",
		Desc:   "删除原材料",
	},

	// ==================== Process 工序 ====================
	{
		Name:   "process.create",
		Path:   "/api/v1/process",
		Method: "POST",
		Domain: "process",
		Action: "create",
		Desc:   "创建工序",
	},
	{
		Name:   "process.list",
		Path:   "/api/v1/process",
		Method: "GET",
		Domain: "process",
		Action: "list",
		Desc:   "工序列表",
	},
	{
		Name:   "process.detail",
		Path:   "/api/v1/process/:id",
		Method: "GET",
		Domain: "process",
		Action: "detail",
		Desc:   "工序详情",
	},
	{
		Name:   "process.update",
		Path:   "/api/v1/process/:id",
		Method: "PUT",
		Domain: "process",
		Action: "update",
		Desc:   "更新工序",
	},
	{
		Name:   "process.delete",
		Path:   "/api/v1/process/:id",
		Method: "DELETE",
		Domain: "process",
		Action: "delete",
		Desc:   "删除工序",
	},

	// ==================== Product 产品 ====================
	{
		Name:   "product.create",
		Path:   "/api/v1/product",
		Method: "POST",
		Domain: "product",
		Action: "create",
		Desc:   "创建产品",
	},
	{
		Name:   "product.list",
		Path:   "/api/v1/product",
		Method: "GET",
		Domain: "product",
		Action: "list",
		Desc:   "产品列表",
	},
	{
		Name:   "product.detail",
		Path:   "/api/v1/product/:id",
		Method: "GET",
		Domain: "product",
		Action: "detail",
		Desc:   "产品详情",
	},
	{
		Name:   "product.update",
		Path:   "/api/v1/product/:id",
		Method: "PUT",
		Domain: "product",
		Action: "update",
		Desc:   "更新产品",
	},
	{
		Name:   "product.delete",
		Path:   "/api/v1/product/:id",
		Method: "DELETE",
		Domain: "product",
		Action: "delete",
		Desc:   "删除产品",
	},
	{
		Name:   "product.cost",
		Path:   "/api/v1/product/:id/cost",
		Method: "POST",
		Domain: "product",
		Action: "cost",
		Desc:   "计算产品成本",
	},

	// ==================== Order 订单 ====================
	{
		Name:   "order.create",
		Path:   "/api/v1/order",
		Method: "POST",
		Domain: "order",
		Action: "create",
		Desc:   "创建订单",
	},
	{
		Name:   "order.list",
		Path:   "/api/v1/order",
		Method: "GET",
		Domain: "order",
		Action: "list",
		Desc:   "订单列表",
	},
	{
		Name:   "order.detail",
		Path:   "/api/v1/order/:id/detail",
		Method: "GET",
		Domain: "order",
		Action: "detail",
		Desc:   "订单详情",
	},
	{
		Name:   "order.events",
		Path:   "/api/v1/order/:id/events",
		Method: "GET",
		Domain: "order",
		Action: "events",
		Desc:   "订单事件列表",
	},
	{
		Name:   "order.assignDepartment",
		Path:   "/api/v1/order/:id/assign-department",
		Method: "POST",
		Domain: "order",
		Action: "assignDepartment",
		Desc:   "分配部门",
	},
	{
		Name:   "order.assignPersonnel",
		Path:   "/api/v1/order/:id/assign-personnel",
		Method: "POST",
		Domain: "order",
		Action: "assignPersonnel",
		Desc:   "分配人员",
	},
	{
		Name:   "order.fabricInput",
		Path:   "/api/v1/order/:id/progress/fabric-input",
		Method: "POST",
		Domain: "order",
		Action: "fabricInput",
		Desc:   "更新胚布投入进度",
	},
	{
		Name:   "order.production",
		Path:   "/api/v1/order/:id/progress/production",
		Method: "POST",
		Domain: "order",
		Action: "production",
		Desc:   "更新生产进度",
	},
	{
		Name:   "order.rework",
		Path:   "/api/v1/order/:id/progress/rework",
		Method: "POST",
		Domain: "order",
		Action: "rework",
		Desc:   "更新回修进度",
	},
	{
		Name:   "order.warehouseCheck",
		Path:   "/api/v1/order/:id/progress/warehouse-check",
		Method: "POST",
		Domain: "order",
		Action: "warehouseCheck",
		Desc:   "更新验货进度",
	},
	{
		Name:   "order.defect",
		Path:   "/api/v1/order/:id/defect",
		Method: "POST",
		Domain: "order",
		Action: "defect",
		Desc:   "录入次品",
	},

	// ==================== Plan 计划 ====================
	{
		Name:   "plan.create",
		Path:   "/api/v1/plan",
		Method: "POST",
		Domain: "plan",
		Action: "create",
		Desc:   "创建计划",
	},
	{
		Name:   "plan.list",
		Path:   "/api/v1/plan",
		Method: "GET",
		Domain: "plan",
		Action: "list",
		Desc:   "计划列表",
	},
	{
		Name:   "plan.detail",
		Path:   "/api/v1/plan/:id",
		Method: "GET",
		Domain: "plan",
		Action: "detail",
		Desc:   "计划详情",
	},
	{
		Name:   "plan.update",
		Path:   "/api/v1/plan/:id",
		Method: "PUT",
		Domain: "plan",
		Action: "update",
		Desc:   "更新计划",
	},
	{
		Name:   "plan.delete",
		Path:   "/api/v1/plan/:id",
		Method: "DELETE",
		Domain: "plan",
		Action: "delete",
		Desc:   "删除计划",
	},

	// ==================== Search 搜索 ====================
	{
		Name:   "search.all",
		Path:   "/api/v1/search",
		Method: "GET",
		Domain: "search",
		Action: "all",
		Desc:   "全局搜索",
	},

	// ==================== Pricing 报价 ====================
	{
		Name:   "pricing.material.list",
		Path:   "/api/v1/pricing/material",
		Method: "GET",
		Domain: "pricing",
		Action: "materialList",
		Desc:   "原材料报价列表",
	},
	{
		Name:   "pricing.material.upsert",
		Path:   "/api/v1/pricing/material",
		Method: "POST",
		Domain: "pricing",
		Action: "materialUpsert",
		Desc:   "设置原材料报价",
	},
	{
		Name:   "pricing.process.list",
		Path:   "/api/v1/pricing/process",
		Method: "GET",
		Domain: "pricing",
		Action: "processList",
		Desc:   "工序报价列表",
	},
	{
		Name:   "pricing.process.upsert",
		Path:   "/api/v1/pricing/process",
		Method: "POST",
		Domain: "pricing",
		Action: "processUpsert",
		Desc:   "设置工序报价",
	},
}

func init() {
	// 自动注册所有接口
	GlobalRegistry.RegisterBatch(AllEndpoints)
}
