// Package docs Code generated by swaggo/swag. DO NOT EDIT
package docs

import "github.com/swaggo/swag"

const docTemplate = `{
    "schemes": {{ marshal .Schemes }},
    "swagger": "2.0",
    "info": {
        "description": "{{escape .Description}}",
        "title": "{{.Title}}",
        "contact": {},
        "version": "{{.Version}}"
    },
    "host": "{{.Host}}",
    "basePath": "{{.BasePath}}",
    "paths": {
        "/auth/login": {
            "post": {
                "description": "通过登录ID和密码进行用户认证",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "认证"
                ],
                "summary": "用户登录",
                "parameters": [
                    {
                        "description": "登录请求参数",
                        "name": "request",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/application.LoginRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "请求参数错误",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    }
                }
            }
        },
        "/auth/logout": {
            "post": {
                "security": [
                    {
                        "Bearer": []
                    }
                ],
                "description": "用户登出（清除 JWT 白名单）",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "认证"
                ],
                "summary": "用户登出",
                "responses": {
                    "200": {
                        "description": "登出成功",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    }
                }
            }
        },
        "/auth/refresh": {
            "post": {
                "description": "使用 Refresh Token 获取新的 Access Token",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "认证"
                ],
                "summary": "刷新访问令牌",
                "parameters": [
                    {
                        "description": "Refresh Token",
                        "name": "request",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/application.RefreshTokenRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "Token 无效",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    }
                }
            }
        },
        "/search": {
            "post": {
                "security": [
                    {
                        "Bearer": []
                    }
                ],
                "description": "基于配置的高级搜索，支持全文搜索、筛选、聚合",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "搜索"
                ],
                "summary": "搜索",
                "parameters": [
                    {
                        "description": "搜索请求参数",
                        "name": "request",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/application.SearchRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "搜索结果",
                        "schema": {
                            "$ref": "#/definitions/application.SearchResponse"
                        }
                    },
                    "400": {
                        "description": "请求参数错误",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    },
                    "500": {
                        "description": "服务器错误",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    }
                }
            }
        },
        "/search/indices": {
            "get": {
                "security": [
                    {
                        "Bearer": []
                    }
                ],
                "description": "获取所有支持搜索的索引列表",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "搜索"
                ],
                "summary": "获取索引列表",
                "responses": {
                    "200": {
                        "description": "索引列表",
                        "schema": {
                            "$ref": "#/definitions/application.IndexListResponse"
                        }
                    }
                }
            }
        }
    },
    "definitions": {
        "application.AggRequest": {
            "type": "object",
            "properties": {
                "after": {
                    "description": "分页游标",
                    "type": "object",
                    "additionalProperties": true
                },
                "search": {
                    "description": "下拉框搜索词",
                    "type": "string"
                },
                "size": {
                    "description": "每页条数（可选，覆盖配置默认值）",
                    "type": "integer"
                }
            }
        },
        "application.AggResult": {
            "type": "object",
            "properties": {
                "after": {
                    "description": "下一页游标",
                    "type": "object",
                    "additionalProperties": true
                },
                "avg": {
                    "type": "number"
                },
                "buckets": {
                    "description": "terms/composite 聚合",
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/application.Bucket"
                    }
                },
                "hasMore": {
                    "description": "是否有更多",
                    "type": "boolean"
                },
                "max": {
                    "type": "number"
                },
                "min": {
                    "description": "stats 聚合",
                    "type": "number"
                }
            }
        },
        "application.Bucket": {
            "type": "object",
            "properties": {
                "docCount": {
                    "type": "integer"
                },
                "key": {}
            }
        },
        "application.IndexListResponse": {
            "type": "object",
            "properties": {
                "indices": {
                    "type": "array",
                    "items": {
                        "type": "string"
                    }
                }
            }
        },
        "application.LoginRequest": {
            "type": "object",
            "required": [
                "loginId",
                "password"
            ],
            "properties": {
                "loginId": {
                    "type": "string"
                },
                "password": {
                    "type": "string",
                    "minLength": 3
                }
            }
        },
        "application.LoginResponse": {
            "type": "object",
            "properties": {
                "accessToken": {
                    "description": "改为小驼峰",
                    "type": "string"
                },
                "department": {
                    "description": "部门信息",
                    "type": "string"
                },
                "refreshToken": {
                    "description": "新增",
                    "type": "string"
                },
                "requirePasswordChange": {
                    "description": "改为小驼峰",
                    "type": "boolean"
                },
                "role": {
                    "description": "扁平化，直接返回角色",
                    "type": "string"
                },
                "username": {
                    "description": "扁平化，直接返回用户名",
                    "type": "string"
                }
            }
        },
        "application.PaginationRequest": {
            "type": "object",
            "properties": {
                "offset": {
                    "type": "integer"
                },
                "size": {
                    "description": "最大 100 条",
                    "type": "integer",
                    "maximum": 100
                }
            }
        },
        "application.RefreshTokenRequest": {
            "type": "object",
            "required": [
                "refreshToken"
            ],
            "properties": {
                "refreshToken": {
                    "type": "string"
                }
            }
        },
        "application.RefreshTokenResponse": {
            "type": "object",
            "properties": {
                "accessToken": {
                    "type": "string"
                }
            }
        },
        "application.SearchRequest": {
            "type": "object",
            "required": [
                "index"
            ],
            "properties": {
                "aggRequests": {
                    "description": "聚合请求",
                    "type": "object",
                    "additionalProperties": {
                        "$ref": "#/definitions/application.AggRequest"
                    }
                },
                "filters": {
                    "description": "筛选条件",
                    "type": "object",
                    "additionalProperties": true
                },
                "index": {
                    "description": "clients, suppliers, orders, etc.",
                    "type": "string"
                },
                "pagination": {
                    "$ref": "#/definitions/application.PaginationRequest"
                },
                "query": {
                    "description": "全文搜索关键词",
                    "type": "string"
                },
                "searchFields": {
                    "description": "指定搜索字段（可选，默认使用配置的queryFields）",
                    "type": "array",
                    "items": {
                        "type": "string"
                    }
                },
                "sort": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/application.SortRequest"
                    }
                }
            }
        },
        "application.SearchResponse": {
            "type": "object",
            "properties": {
                "aggregations": {
                    "description": "聚合结果",
                    "type": "object",
                    "additionalProperties": {
                        "$ref": "#/definitions/application.AggResult"
                    }
                },
                "items": {
                    "description": "搜索结果",
                    "type": "array",
                    "items": {
                        "type": "object",
                        "additionalProperties": true
                    }
                },
                "took": {
                    "description": "耗时 (ms)",
                    "type": "integer"
                },
                "total": {
                    "description": "总条数",
                    "type": "integer"
                }
            }
        },
        "application.SortRequest": {
            "type": "object",
            "properties": {
                "field": {
                    "type": "string"
                },
                "order": {
                    "description": "asc, desc",
                    "type": "string"
                }
            }
        }
    },
    "securityDefinitions": {
        "Bearer": {
            "description": "请输入 Bearer {token}",
            "type": "apiKey",
            "name": "Authorization",
            "in": "header"
        }
    }
}`

// SwaggerInfo holds exported Swagger Info so clients can modify it
var SwaggerInfo = &swag.Spec{
	Version:          "1.0",
	Host:             "",
	BasePath:         "/api/v1",
	Schemes:          []string{},
	Title:            "后台管理系统 API",
	Description:      "后台管理系统的API文档",
	InfoInstanceName: "swagger",
	SwaggerTemplate:  docTemplate,
	LeftDelim:        "{{",
	RightDelim:       "}}",
}

func init() {
	swag.Register(SwaggerInfo.InstanceName(), SwaggerInfo)
}
